package com.dugzzuli.dug.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.dugzzuli.dug.entity.News;

public interface NewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    int insert(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    int insertSelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    News selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    int updateByPrimaryKeySelective(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(News record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table news
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    int updateByPrimaryKey(News record);

	List<News> selectAll();
	
	List<News> selectAllNews(@Param("order")String order, @Param("count")int count);

	List<News> selectHotNews(@Param("hot")String hot, @Param("count")int count);

	News selectByPrimaryKey(@Param("id")int id);

	News selectModel(@Param("about")String about);
}