package com.dugzzuli.dug.service;

import com.dugzzuli.dug.entity.Sysuser;

public interface ISysuser {
	  /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysuser
     *
     * @mbg.generated Sat Aug 11 15:03:33 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysuser
     *
     * @mbg.generated Sat Aug 11 15:03:33 CST 2018
     */
    int insert(Sysuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysuser
     *
     * @mbg.generated Sat Aug 11 15:03:33 CST 2018
     */
    int insertSelective(Sysuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysuser
     *
     * @mbg.generated Sat Aug 11 15:03:33 CST 2018
     */
    Sysuser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysuser
     *
     * @mbg.generated Sat Aug 11 15:03:33 CST 2018
     */
    int updateByPrimaryKeySelective(Sysuser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sysuser
     *
     * @mbg.generated Sat Aug 11 15:03:33 CST 2018
     */
    int updateByPrimaryKey(Sysuser record);

	Sysuser selectModel(Sysuser model);
}
