package com.dugzzuli.dug.entity;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.id
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cate_id
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    private String cateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cate_name
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    private String cateName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.id
     *
     * @return the value of category.id
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.id
     *
     * @param id the value for category.id
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cate_id
     *
     * @return the value of category.cate_id
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    public String getCateId() {
        return cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cate_id
     *
     * @param cateId the value for category.cate_id
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    public void setCateId(String cateId) {
        this.cateId = cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cate_name
     *
     * @return the value of category.cate_name
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    public String getCateName() {
        return cateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cate_name
     *
     * @param cateName the value for category.cate_name
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    public void setCateName(String cateName) {
        this.cateName = cateName;
    }
}