package com.dugzzuli.dug.entity;

import java.util.Date;

public class News {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.id
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.news_title
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    private String newsTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.creatdate
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    private Date creatdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.author
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.pic
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    private String pic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.updatedate
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    private Date updatedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.category
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    private String category;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column news.content
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.id
     *
     * @return the value of news.id
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.id
     *
     * @param id the value for news.id
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.news_title
     *
     * @return the value of news.news_title
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    public String getNewsTitle() {
        return newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.news_title
     *
     * @param newsTitle the value for news.news_title
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.creatdate
     *
     * @return the value of news.creatdate
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    public Date getCreatdate() {
        return creatdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.creatdate
     *
     * @param creatdate the value for news.creatdate
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    public void setCreatdate(Date creatdate) {
        this.creatdate = creatdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.author
     *
     * @return the value of news.author
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.author
     *
     * @param author the value for news.author
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.pic
     *
     * @return the value of news.pic
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.pic
     *
     * @param pic the value for news.pic
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    public void setPic(String pic) {
        this.pic = pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.updatedate
     *
     * @return the value of news.updatedate
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    public Date getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.updatedate
     *
     * @param updatedate the value for news.updatedate
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    public void setUpdatedate(Date updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.category
     *
     * @return the value of news.category
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    public String getCategory() {
        return category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.category
     *
     * @param category the value for news.category
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    public void setCategory(String category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column news.content
     *
     * @return the value of news.content
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column news.content
     *
     * @param content the value for news.content
     *
     * @mbg.generated Sat Aug 11 10:23:05 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }
}