package com.dugzzuli.dug.entity;

import java.util.Date;

public class Sysuser {
    @Override
	public String toString() {
		return "Sysuser [id=" + id + ", userName=" + userName + ", userPwd=" + userPwd + ", updateTime=" + updateTime
				+ ", sys=" + sys + "]";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.id
     *
     * @mbg.generated Sat Aug 11 15:03:33 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.user_name
     *
     * @mbg.generated Sat Aug 11 15:03:33 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.user_pwd
     *
     * @mbg.generated Sat Aug 11 15:03:33 CST 2018
     */
    private String userPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.update_time
     *
     * @mbg.generated Sat Aug 11 15:03:33 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sysuser.sys
     *
     * @mbg.generated Sat Aug 11 15:03:33 CST 2018
     */
    private String sys;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.id
     *
     * @return the value of sysuser.id
     *
     * @mbg.generated Sat Aug 11 15:03:33 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.id
     *
     * @param id the value for sysuser.id
     *
     * @mbg.generated Sat Aug 11 15:03:33 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.user_name
     *
     * @return the value of sysuser.user_name
     *
     * @mbg.generated Sat Aug 11 15:03:33 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.user_name
     *
     * @param userName the value for sysuser.user_name
     *
     * @mbg.generated Sat Aug 11 15:03:33 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.user_pwd
     *
     * @return the value of sysuser.user_pwd
     *
     * @mbg.generated Sat Aug 11 15:03:33 CST 2018
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.user_pwd
     *
     * @param userPwd the value for sysuser.user_pwd
     *
     * @mbg.generated Sat Aug 11 15:03:33 CST 2018
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.update_time
     *
     * @return the value of sysuser.update_time
     *
     * @mbg.generated Sat Aug 11 15:03:33 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.update_time
     *
     * @param updateTime the value for sysuser.update_time
     *
     * @mbg.generated Sat Aug 11 15:03:33 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sysuser.sys
     *
     * @return the value of sysuser.sys
     *
     * @mbg.generated Sat Aug 11 15:03:33 CST 2018
     */
    public String getSys() {
        return sys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sysuser.sys
     *
     * @param sys the value for sysuser.sys
     *
     * @mbg.generated Sat Aug 11 15:03:33 CST 2018
     */
    public void setSys(String sys) {
        this.sys = sys;
    }
}